---
- name: Playbook para validar comunicación con API de OpenShift
  hosts: localhost
  tasks:
    - name: Validar comunicación con API de OpenShift obteniendo información de los pods
      k8s_info:
        api_key: "{{ lookup('env', 'K8S_AUTH_API_KEY') }}"  # Asegúrate de que el token esté disponible como variable de entorno
        host: "https://api.sno.labjp.xyz:6443"  # Cambia esta URL por la URL de tu API de OpenShift
        verify_ssl: no  # Cambia a "yes" si usas certificados válidos
        kind: Pod
        namespace: default  # Cambia al namespace que desees consultar
      register: pods_info

    - name: Mostrar la lista de pods del namespace default
      debug:
        msg: "{{ pods_info.resources | map(attribute='metadata.name') | list }}"

    - name: Crear un archivo de prueba si la API responde correctamente
      file:
        path: /tmp/archivo_prueba_api_openshift.txt
        state: touch
